### ISSUE TITLE
"Active" balance observer doesn't work on Solana

### ISSUE THREAD

**Issue by showered** [kinecosystem/kin-android#11]
`base` version `0.4.0`.

As per the title of the issue, when using the `Active` balance observer, balance updates are not triggered at all. Neither for earns nor spends.

When using `Passive`, the balance reduces when spending, but never goes back up when earning.

This issue only occurs when using the **Solana** blockchain. *i.e.* When using `testMigration()` and `Environment.KinStellarTestNet`.

**Comment by chaseeb** [comment]
a fix is currently being worked to resolve it. and will not require and update of the SDKs.
