### ISSUE TITLE
p2p txn `type` broken in BaseCompat in kin-android@0.4.3 thru 0.4.5, should be "P2P" but is "Unknown"

### ISSUE THREAD

**Issue by rorymc** [kinecosystem/kin-android#12]
noticed that Android Kin BaseCompat has a bug:
• Android:  p2p txn `type` is `Unknown` instead of `P2P`    kin-android@0.4.5
• iOS:  properly has `type` properly set to `P2P`     kin-ios@0.4.1

I’m not sure if this applies to after Solana migration or not.. just fyi.

why i’m noting:
• we were checking the type of txn on the blockchain, so that we could validate something
• our previous code was working with checking the type of the txn was P2P, and then we needed to add an exception only for Android

**Comment by chaseeb** [comment]
resolved
