### ISSUE TITLE
Custom storeKey not working anymore

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/kin-android#14]
I built kinfit using a storeKey of "user1". Don't ask me why, but it is what it is. However, the 0.4.x version of base-compat doesn't allow custom storeKeys anoymore, leading to all wallets not being found anymore. I had to clone the project and change it locally to get it working, but that's not really a solution.

Please bring this functionality back, thanks!

**Comment by l-hendriks** [comment]
I tried to temp fix this by checking out this project locally and updating the code, but it's just not working out. I spent hours trying to fix compile errors but it's just not working out, and the fix should be very simple for you

**Comment by l-hendriks** [comment]
This is the error:

```
/Users/luc/Projects/kinfit/app/android/app/src/main/java/com/kinsdk/RNKinSdkModule.java:99: error: cannot access AppInfoProvider
                this.client = new KinClient(this.reactContext, Environment.TEST, appId, "user1");
                              ^
  class file for org.kin.sdk.base.network.services.AppInfoProvider not found
```

**Comment by l-hendriks** [comment]
I got it working by creating a dummy app info provider like this:

```
class DummyAppInfoProvider implements AppInfoProvider {

    private AppInfo appinfo = new AppInfo(new AppIdx(0), new org.kin.sdk.base.models.KinAccount.Id(new byte[0]), "", 123);

    public AppInfo getAppInfo() {
        return appinfo;
    }

    public AppUserCreds getPassthroughAppUserCredentials() {
        return new AppUserCreds("", "");
    }
}
```

And then using a different constructor like this:

```
this.client = new KinClient(this.reactContext, Environment.TEST, appId, "user1", new DummyAppInfoProvider());
```

And adding the base SDK to the dependencies (as well as the base-compat SDK) and then dealing with the duplicate dependencies :)

**Comment by chaseeb** [comment]
Has this been resolved?

**Comment by l-hendriks** [comment]
Well not really, my solution is an ugly workaround. The good fix would be to fix the constructor with the right signature in KinClient

But I guess no one uses custom storekeys anyways, so I'm not sure it's worth it.

**Comment by Blahartinger** [comment]
KinClient has been removed as of 1.0.0
