### ISSUE TITLE
Unable to compile base-compat past 0.4.1

### ISSUE THREAD

**Issue by CWftw** [kinecosystem/kin-android#15]
In 0.4.2 and onward we get a compilation error when initializing a KinAccount:
`class file for org.kin.sdk.base.network.services.AppInfoProvider not found`
The class in not exposed in base-compat.

As a temporary workaround I have included base as follows:
`api ('org.kin.sdk.android:base:0.4.5') {
        exclude module: 'libsodium-jni'
    }`

**Comment by Blahartinger** [comment]
base-compat has been slimmed down to only backup and restore as of 1.0.0
