### ISSUE TITLE
getPassthroughAppUserCredentials() override is not fired for API version 4

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/kin-android#17]
When using API version 4 of the environment, I cannot get `getPassthroughAppUserCredentials()` to fire when sending out a transaction.

I think there is a problem with [AppUserAuthInterceptor.kt](https://github.com/kinecosystem/kin-android/blob/a34cd50a2136cda9884c9ee8e34f3489c6a51382/base/src/main/java/org/kin/sdk/base/network/api/agora/AppUserAuthInterceptor.kt) here:

```kotlin
    if (method?.fullMethodName == "kin.agora.transaction.v3.Transaction/SubmitTransaction") {
         val creds = appInfoProvider.getPassthroughAppUserCredentials()
         headers.put(HEADER_KEY_APP_USER_ID, creds.appUserId)
         headers.put(HEADER_KEY_APP_USER_PASSKEY, creds.appUserPasskey)
     }
```

**Comment by hitwill** [comment]
I don't know if this is related, but the networkPassphrase is also hitting the server with the value `undefined`

**Comment by Blahartinger** [comment]
will include this in 0.4.7
