### ISSUE TITLE
Possible bug in class `ValueSubject`

### ISSUE THREAD

**Issue by gmpassos** [kinecosystem/kin-android#19]
Method `dispose()`, calls `onDisposed.forEach` and `onDisposed.clear` for each element in `listeners`:
https://github.com/kinecosystem/kin-android/blob/master/base/src/main/java/org/kin/sdk/base/tools/Observers.kt#L112

It should called only once. They should be outside of the `listeners.forEach` call.

**Comment by Blahartinger** [comment]
Thanks. Will include in 0.4.7

**Comment by Blahartinger** [comment]
fixed
