### ISSUE TITLE
Getting Started Base guide is outdated and confusing

### ISSUE THREAD

**Issue by samdowd** [kinecosystem/kin-android#20]
Tried migrating from BaseCompat to Base, and this is where I ran into problems:

- Initializing KinEnvironment code uses values stored in the demo app like DemoAppConfig.DEMO_APP_ACCOUNT_ID. It wasn't clear what I should put there or even what an account id was. Would be better if the getting started docs just skipped that abstraction and showed a real example in the form `KinAccount.Id("GDV4...")` and same for the app index. I had to go into the demo app and find the config class just to figure out the `AppIdx()` convention.
- Remove references to "upcoming" migration
- Unclear how to load an existing account from BaseCompat. On a testing phone with a Kin account from BaseCompat, KinEnvironment.allAccountIds() returns an empty list, and it looks like the other options require a private key? Which we were always recommended not to store. If we need to access it by private key here, include a section on how to get the private keys that were stored by BaseCompat.

There may be more, but I'm now stuck and can't check the rest

**Comment by hitwill** [comment]
Thanks @samdowd - For the short term, there is a simple implementation here: https://kintegrate.dev/starters/kin-android-starter

The docs should be updated with the milestones

**Comment by samdowd** [comment]
Thanks, Will! Just trying to help out where I can. Happy to wait for the next milestone.

**Comment by Blahartinger** [comment]
> Initializing KinEnvironment code uses values stored in the demo app like DemoAppConfig.DEMO_APP_ACCOUNT_ID. 
It's your app index
> Remove references to "upcoming" migration
has been done as of 1.0.0
> Unclear how to load an existing account from BaseCompat
has been trashed in 1.0.0 aside from backup and restore UI
