### ISSUE TITLE
Demo app no longer works

### ISSUE THREAD

**Issue by mocolicious** [kinecosystem/kin-android#21]
The demo app needs to be updated to use the solana implementation and demo the use of Agora.  Currently it doesn't work.

**Comment by mocolicious** [comment]
Create account works, fund account does not work in the demo.  Workaround is to do it using https://kin-drops.herokuapp.com/?YOUR_APP_ADDRESS

**Comment by hitwill** [comment]
There's some nuance to fundAccount. The airdrop RPC expects the token account address (not a Stellar type or Solana account owner), and rejects it otherwise. (This will not be an issue with the next release of the SDK)

**Comment by mocolicious** [comment]
> There's some nuance to fundAccount. The airdrop RPC expects the token account address (not a Stellar type or Solana account owner), and rejects it otherwise. (This will not be an issue with the next release of the SDK)

we should fix the demo.
