### ISSUE TITLE
Unable to watch for changes to the kin account

### ISSUE THREAD

**Issue by xingyi0201** [kinecosystem/kin-android#24]
I am not able to watch for changes to the kin account when I build KinAccountContext using the importExistingPrivateKey method.
https://github.com/kintegrate/kin-starter-kotlin/blob/master/app/src/main/java/com/kin/kin/Kin.kt#L174

There are two methods to build KinAccountContext I think.

1. KinAccountContext.Builder(testKinEnvironment)
          .createNewAccount()
          .build()
2. KinAccountContext.Builder(testKinEnvironment)
          .importExistingPrivateKey(Key.PrivateKey(secret))
          .build()

When I use the createNewAccount method, I could listen to future account balance changes. But in the case of the second one, it's not working

**Comment by showered** [comment]
There are 3 ways to load an account, actually. Try `useExistingAccount(Id(stellarPublicAddress))`

Maybe the balance observer works better that way?

**Comment by xingyi0201** [comment]
I already tried that method. but no lucks :(

**Comment by hitwill** [comment]
Confirmed for both Balances and Payment listeners.

They only fire when requestInvalidation() is called. When called, the balance event fires as normal. The payment event fires but returns an empty array

**Comment by hitwill** [comment]
Fixed in v1 release
