### ISSUE TITLE
1.0.0 - mergeAccountsFailure when using kinAccountContext.getAccount()

### ISSUE THREAD

**Issue by bluemods** [kinecosystem/kin-android#25]
When using `getAccount()` from `KinAccountContext`, it works, but about 10-15 seconds later, this error prints:

`mergeAccountsFailure: {org.kin.sdk.base.network.services.KinService$FatalError$TransientFailure: java.io.IOException: The request was retried until limit was exceeded}`

I am using JDK 15.0.2 if that helps.

**Comment by Blahartinger** [comment]
An extra check in 1.0.1 has been added to not attempt merging when you have < 2 token accounts. The message is not actually driven from he getAccount() code path but from the initialization of KinAccountContext. The message is really superfluous but shouldn't be there now for you in the case where you didn't need to merge.
