### ISSUE TITLE
Sending to a token account creates a child token account

### ISSUE THREAD

**Issue by showered** [kinecosystem/kin-android#26]
**What's the problem?**

If you send Kin from the Android SDK to a SOL address, the Kin is transferred to the Solana account's *associated token account*. If no account is found, a new one is created. This works well.

If you send Kin from the Android SDK to a Token Account address, then a new token account is created as a child of the token account originally intended as the destination.

**What's the solution?**

The SDK should check the destination account to see if it is an *owner* or a *token*. If it is not an owner, DO NOT create a new token account inside it.

**Comment by Blahartinger** [comment]
This has been resolved in 1.0.1
