### ISSUE TITLE
Cannot access child Kin token accounts

### ISSUE THREAD

**Issue by showered** [kinecosystem/kin-android#27]
**What's happening?**

As per https://github.com/kinecosystem/kin-android/issues/26, it is possible to create Kin token accounts as children of other Kin token accounts. 

As far as I know, this Kin is inaccessible via MyKinWallet or the SDK.

Example here:
https://explorer.solana.com/address/DHNkh3wVgyrnkxoJj7EG9oBeiMiBXGih5EzdR4zRtyKD

**What's the solution?**

- The "merge accounts" feature could sort all this out for us
- MyKinWallet could be adapted to allow access to the child accounts

**Comment by Blahartinger** [comment]
These accounts are _likely_ burned and unaccessible as you won't have the owner pk's. An extra check has been added in 1.0.1
